name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest    
    permissions:
      id-token: write
      contents: read
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.5
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ AWS_ACCOUNT_ID }}:role/github-oidc/github-deployment

    - name: Initialize Terraform
      run: terraform init -backend-config="bucket=tf-state-${{ AWS_REGION }}-${{ AWS_ACCOUNT_ID }}" -backend-config="key=${{ GITHUB_REPOSITORY }}.tfstate" -backend-config="dynamodb_table=tf-state-${{ AWS_REGION }}-${{ AWS_ACCOUNT_ID }}"
      
    - name: Plan Terraform
      run: terraform plan -out=tfplan
      
    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
