name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  permissions:
    id-token: write

  deploy:
    name: Deploy Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.5
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: arn:aws:iam::932191515807:role/github-oidc/github-deployment

    - name: Initialize Terraform
      run: terraform init
      
    - name: Plan Terraform
      run: terraform plan -out=tfplan
      
    - name: Apply Terraform
      run: terraform apply -auto-approve tfplan
